### ISSUE TITLE
rounded props for a card throws an error

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew#32]
![image](https://user-images.githubusercontent.com/48761741/219275694-8e343267-7e2f-4e2e-924a-04dd6656f128.png)

This error pops up when I use `rounded` props for cards. 

![image](https://user-images.githubusercontent.com/48761741/219276082-81572733-3519-4d7c-9c23-6bf6d865d44b.png)

**Comment by jbtrystram** [comment]
The rounded prop was added last week, and not released yet. If you want to use this make sure to patch the dependency in your `Cargo.toml` file and point it to the repo main branch . 
That's probably why you have this issue. 

Also, for the future : please don't post screen captures of code, simply copy and paste the text, it's easier to read :)

**Comment by ctron** [comment]
You can use the latest version from git using:

```toml
[patch.crates-io]
patternfly-yew = { git = "https://github.com/ctron/patternfly-yew" }
```

Just be sure that the version requirement in your main dependencies section matches the version in the main branch.

For more information, see: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
