### ISSUE TITLE
Error "the trait `HasProp<patternfly_yew::page::_Props::children, _>` is not implemented for `AssertAllProps`"

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew#34]
![image](https://user-images.githubusercontent.com/48761741/223453930-83f9f3ea-9f4d-4616-8d0c-d96ffbcd6026.png)

I am not sure why I get this error ...

```rs
#[function_component(NavSideBar)]
pub fn navbar_component() -> Html{
   let children = html!(<h3>{"Home"}</h3>);
   let logo = html!{<img src="./img/logipsum195.svg" />};
   html!{
         <Page logo={logo}></Page>
   }
}

**Comment by ctron** [comment]
This is a weird way of Yew saying: You are missing a value for the property `children` and it doesn't have a default.

I think it might make sense to allow for a default children value. If you have nothing, then there is nothing.
