### ISSUE TITLE
I am not able to pass the iterator to Select's children

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew#35]
I am getting the error "the trait `From<VNode>` is not implemented for `SelectChildVariant<std::string::String>`" when I try to do the following: What could I be missing?

![image](https://user-images.githubusercontent.com/48761741/224728811-d17c40f7-a168-452b-a0bf-55243bfb5fec.png)

```rs

#[function_component(AddItem)]
pub fn _view() -> Html{
    let brand_vec = vec!["Nike".to_string(), "Puma".to_string(), "Sonny".to_string(), "Adidas".to_string()];
    let nike = &brand_vec[0];
    let puma = &brand_vec[1];
    let adidas = &brand_vec[3];

    let options = brand_vec.iter().map(|brand| {
        let brand = brand.clone();
        html!{
            <select class="form-control">
                <option value="{&brand}">{brand}</option>
            </select>
        }
    }).collect::<Html>();

    html!{
        <>
            <div>
                <Select<String>  placeholder="Select Brand">
                    // <SelectOption<String> value={nike.clone()} />
                    // <SelectOption<String> value={puma.clone()} />
                    // <SelectOption<String> value={adidas.clone()} />
                    {options}
                </Select<String>>
            </div>
        </>
    }
}
```

**Comment by ctron** [comment]
So, `Select` requires a `SelectOption` or `SelectGroup`, you seem to be passing in a `select` (which is the "standard" HTML select element. Either of them can be "intoed" into `SelectChildVariant`.

The commented out code should work: https://ctron.github.io/patternfly-yew-quickstart/component/select

Also, when you collect it the way you did, it will end up as `Html`, which also isn't compatible with `SelectChildVariant`. You can however use `html_nested!` to use the actual type. Note that this however extracts only the type of the root element. So if you want to have more than one prepare in a collection, you need to collect a `Vec` of `html_nested!` calls.

**Comment by ctron** [comment]
I would do it like this: https://github.com/seedwing-io/seedwing-policy/blob/3640ae2985c2b5d8b1d2ef00d83c5662ac363315/frontend/src/pages/policy/mod.rs#L473-L484

**Comment by collinsmarra** [comment]
Thank you

**Comment by ctron** [comment]
I assume it worked for you, so I will close the issue. If that's not the case, let me know and we can re-open it.
