### ISSUE TITLE
Collapsing tree component inside a form crashes and reloads the page

### ISSUE THREAD

**Issue by aDogCalledSpot** [ctron/patternfly-yew#42]
I want to make a [tree with checkboxes](https://www.patternfly.org/v4/components/tree-view/#with-checkboxes) as part of a form. I used the tree code from the quickstart (no checkboxes for now) and realized that collapsing part of the tree briefly looks correct but then crashes. Moving the component outside of the form lets everything work correctly:

Example code:
```rust
#[function_component(AddChannelForm)]
pub fn add_channel() -> Html {
    html! {
        <Form>
            <FormGroup label="Name">
                <next::TextInput
                required=true/>
            </FormGroup>
            <FormGroup>
                <ComponentSelector/>
            </FormGroup>
            <ActionGroup>
                <Button variant={ButtonVariant::Primary} label="Submit" r#type={ButtonType::Submit}/>
            </ActionGroup>
        </Form>
    }
}

// !!!! This is just the tree example code from the quickstart
#[function_component(ComponentSelector)]
pub fn component_selector() -> Html {
    let header = html_nested! {
        <TreeTableHeader>
            <TableColumn label="foo" width={ColumnWidth::Percent(40)}/>
            <TableColumn label="L1" width={ColumnWidth::Percent(20)}/>
            <TableColumn label="L2" width={ColumnWidth::Percent(20)}/>
            <TableColumn label="L3" width={ColumnWidth::Percent(20)}/>
        </TreeTableHeader>
    };

    #[derive(PartialEq)]
    struct Root {
        root: Rc<Node>,
    }

    #[derive(PartialEq)]
    enum Node {
        Branch(Vec<String>, Vec<Rc<Node>>),
        Leaf(Vec<String>)
    }

    impl TreeTableModel for Root {
        fn children(&self) -> Vec<Rc<dyn TreeNode>> {
            self.root.children()
        }
    }

    impl TreeNode for Node {
        fn render_main(&self) -> Cell {
            match self {
                Self::Branch(name, _) => html!({name.join(" / ")}),
                Self::Leaf(name) => html!({name.join(" / ")}),
            }.into()
        }

        fn render_cell(&self, context: CellContext) -> Cell {
            let name = match self {
                Self::Branch(name, _) | Self::Leaf(name) => name,
            };

            // quick alternative to: match context.column { 0=> {}, … }
            name.get(context.column)
                .map(Html::from)
                .unwrap_or_default()
                .into()
        }

        fn children(&self) -> Vec<Rc<dyn TreeNode>> {
            match self {
                Self::Branch(_, children) => children.iter().map(|c|c.clone() as Rc<dyn TreeNode>).collect(),
                Self::Leaf(_) => vec![],
            }
        }
    }

    let mut root = vec![];
    for a in ["I", "II", "III"] {
        let mut folders = vec![];
        for b in [1,2,3] {
            let mut leaves = vec![];
            for c in ["a", "b", "c"] {
                leaves.push(Rc::new(Node::Leaf(vec![a.to_string(), b.to_string(), c.to_string()])));
            }
            folders.push(Rc::new(Node::Branch(vec![a.to_string(), b.to_string()], leaves)));
        }
        root.push(Rc::new(Node::Branch(vec![a.to_string()], folders)));
    }

    let root = Rc::new(Root {root: Rc::new(Node::Branch(vec![], root))});

    html!{
        <TreeTable<Root>
            mode={TreeTableMode::Compact}
            header={header}
            model={root}
        />
    }
}
```

If using a tree here isn't intended, then there should maybe be some trait bounds, so it isn't usable here.

**Comment by ctron** [comment]
I think having a tree inside a form should just work. On the other side, the tree stuff is pretty new and experimental.

What sounds a bit weird to me is the "reloading" part. If you're using `trunk serve`, that might trigger a reload because of a code change. And trunk might compile a few times too often, which might lead to a few reloads after a change. If that's the case, then simply some patience is requires, or the patched `trunk` version which fixes this.

A crash can indeed happen, but that would be a `panic`, and should be visible in the browser's console. If that's the case, then it would be good to have this information, because that would tell us what is wrong.

**Comment by aDogCalledSpot** [comment]
This also has me confused. I don't see anything from trunk, the developer console in my browser doesn't output anything and trunk doesn't recompile at all.

Here's a brief video for reference. The same thing happens in the example I posted above.

[Screencast 2023-05-23 16:51:28.webm](https://github.com/ctron/patternfly-yew/assets/22723953/7c39afd9-6754-46ba-81af-6f0dd55ac74d)

I'm running in this in Firefox.

**Comment by ctron** [comment]
Hm, this looks interesting indeed. It feels like the click on the toggle navigates away from the page, causing the reload. So maybe there is some event bubbling up.

It would be great if you could share a reproducer. That might help.

**Comment by ctron** [comment]
> Minimal example here: https://github.com/aDogCalledSpot/patternfly-test

404 :wink:

**Comment by aDogCalledSpot** [comment]
Sorry, visibility of the project has been updated.

**Comment by ctron** [comment]
So it looks like it is reloading:

![image](https://github.com/ctron/patternfly-yew/assets/202474/3fb5a0b5-f3df-465e-9a2b-33a1109d2c87)

Enabling the persistent console option shows it.

**Comment by ctron** [comment]
Ok, found it! the button of the toggle must have the `type` attribute set to `button`, otherwise it is `submit`, which triggers a form submission. Which also explains the behavior you saw and why we didn't encounter it so far :)

**Comment by ctron** [comment]
If you update the git rev, you should have a fix! And thanks for the reproducer, this really helped!

**Comment by aDogCalledSpot** [comment]
Can confirm that it works :grin: 

Thank you so much for the quick help! I really appreciate this repository and the work you're putting into it!
