### ISSUE TITLE
`Pagination` Component `navigation_callback` does not allow navigation to next/last/previous/page(x)

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew#45]
```rs
...
 // let onset_per_page =
    let limit_callback ={
        use_callback(move |number, limit|{
            limit.set(number)
        }, limit.clone())
    };

    let nav = use_state(|| Navigation::First);
    let nav_callback = {
        use_callback(move |_page: Navigation, nav|{
            gloo::console::log!("clicked next page");
            nav.set(Navigation::Page(2));
        }, nav.clone())
    };
    html!{
        <div>
            <Pagination
                total_entries={Some(raw_elemets.len() as u32)}
                offset={offset.deref()}
                entries_per_page_choices={vec![5, 10, 25,50,100]}
                selected_choice={*limit.deref()}
                limit_callback={limit_callback}
                navigation_callback={nav_callback}
                    />
            <Table<SharedTableModel<NumbersTable>>
                header={table_headers}
                entries={entries}
                mode={TableMode::Compact}/>
        </div>
    }
}
```

so I would click the arrows to indicate the next page but I wouldn't go to the next page

![image](https://github.com/ctron/patternfly-yew/assets/48761741/39ddc5ec-c739-4db6-943c-1565d6537e4e)

**Comment by ctron** [comment]
I haven't used that myself so far, but I need to take a look at this today anyway, so I will take a look.

Maybe @jbtrystram can help.

**Comment by ctron** [comment]
I added an example in the quickstart repo, and I think it mostly works: https://github.com/ctron/patternfly-yew-quickstart/tree/main/src/components/pagination

What doesn't work (at least the way I expect it) is to enter a specific page, as that state gets overwritten by the properties.

I also have an issue in the quickstart example where it runs beyond the "max" items, but that's a bug in the quickstart code.

**Comment by jbtrystram** [comment]
@collinsmarra I wrote that code quite some time ago, so i am not sure what is going wrong there. 
I don´t recall having that issue. The pagination was mostly working appart the specific page field.
Could you link a reproducer  somewhere so I can investigate ? 
Maybe the example @ctron published will help you ? 

There is also a use of this pagination component here : https://github.com/drogue-iot/drogue-cloud/blob/8aa49b2482442bb13d54d97a308a16f476ace203/console-frontend/src/pages/devices/index.rs#L228

**Comment by ctron** [comment]
Thanks for the feedback. I that solves your issue, I would kindly as you to close the issue. Otherwise, maybe re-phrase in what you think needs fixing (even it that is documentation).

**Comment by ctron** [comment]
Is a reference to the quickstart enough?

**Comment by collinsmarra** [comment]
It is more than enough.
